name: Build Master

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: npm ci
      - run: npm run lib:build --if-present
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build Quarkus Testserver with Maven
        working-directory: ./dev/servers/quarkus
        run: mvn --batch-mode --update-snapshots verify

